### ISSUE TITLE
add auto sleep

### ISSUE THREAD

**Issue by supmyhava** [dwisyafriadi/bits#1]
add sleep mode 
after finish all tasks make it sleep for 24 hours

**Comment by dwisyafriadi** [comment]
Thank you for your input. We will immediately

**Comment by dwisyafriadi** [comment]
already add it. Please git pull

**Comment by supmyhava** [comment]
> already add it. Please git pull

after 24 hours

All processes complete. Starting cooldown for 24 hours...
Cooldown complete!5:29
Traceback (most recent call last):
  File "/root/bits/bits.py", line 194, in <module>
    main()
    ^^^^
NameError: name 'main' is not defined. Did you mean: 'min'?

**Comment by supmyhava** [comment]
also btw its not claim tasks its only clicks them
